sonar.projectKey=racewalk-tournament
sonar.projectName=racewalk-tournament
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.md,**/semgrep-results.json,sonar-project.properties,**/*.lock,package-lock.json,**/coverage/**
sonar.sourceEncoding=UTF-8

# Tests & coverage
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
