sonar.projectKey=racewalk-tournament
sonar.projectName=racewalk-tournament
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.md,**/semgrep-results.json,sonar-project.properties,**/*.lock,package-lock.json
sonar.sourceEncoding=UTF-8
